const REPORT_REDUX_CONSTANT = {
  GET_ACTIVITY_BREAKDOWN: 'GET_ACTIVITY_BREAKDOWN',
  GET_PIPELINE_VALUES: 'GET_PIPELINE_VALUES',
  GET_CONVERSATION_GRAPH_DATA: 'GET_CONVERSATION_GRAPH_DATA',
};
export default REPORT_REDUX_CONSTANT;
