const DASHBOARD_REDUX_CONSTANT = {
  OPPRTUNITIES_REDUX_CONSTANT: 'OPPRTUNITIES_REDUX_CONSTANT',
  PIPELINE_REDUX_CONSTANT: 'PIPELINE_REDUX_CONSTANT',
  CLIENT_QUOTE: 'CLIENT_QUOTE',
};
export default DASHBOARD_REDUX_CONSTANT;
