const FILTER_REDUX_CONSTANT = {
  UPDATE_STAGE_CHECKBOX: 'UPDATE_STAGE_CHECKBOX',
  RESET_STAGE_FILTER: 'RESET_STAGE_FILTER',
  RESET_POTENTIAL_FILTER: 'RESET_POTENTIAL_FILTER',
};
export default FILTER_REDUX_CONSTANT;
